import "./globals.css";
import {Rubik, Roboto, Nunito_Sans, Montserrat} from "next/font/google";

import {Providers} from "@/components";
import Favicon from "/public/images/Metadata/favicon.ico";

const rubik = Rubik({subsets: ["latin"]});
const nunitoSans = Nunito_Sans({subsets: ["latin"]});
const montserrat = Montserrat({subsets: ["latin"]});
const roboto = Roboto({subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"]});

export const metadata = {
    title: "Recial",
    description: "Generated by create next app",
    icons: [{ rel: "icon", url: Favicon.src }],
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={`${nunitoSans.className}`}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
